#!/bin/bash

echo -e "\nWindows binaries generator\n"

(uname | grep -i "cygwin") || { echo -e "This script runs only under the cygwin environment\n(unix-like environment for windows) !!!\n"; exit 1; }

echo
echo "running"

dest=winbinaries
disks=disks

# echo -e "\nremove directory $dest"
# rm -rf $dest
echo "create $dest"
mkdir $dest

echo -e "\ncopy exe-files to $dest"
strip cdm.exe
cp -v cdm.exe $dest
strip yaze_bin.exe
cp -v yaze_bin.exe $dest

echo -e "\ncopy mintty.exe"
cp -v /bin/mintty.exe $dest

echo -e "\ncopy cygwin1.dll"
cp -v /bin/cygwin1.dll $dest

echo -e "\ncopy stty.exe to $dest"
cp -v /usr/bin/stty.exe $dest
cp -v /usr/bin/cygintl-8.dll $dest
cp -v /usr/bin/cygiconv-2.dll $dest

echo -e "\ncopy batch and boot files to $dest"
cp -v yaze.bat yaze-cpm3.boot yaze.boot $dest


echo -e "\nBegin copy disks to $dest/$disks"
echo "create $dest/$disks"
mkdir $dest/$disks
for ydsk in `cat doc_ydskfiles.txt` ; do
   cp -v $ydsk $dest/$disks/$ydsk
done

echo "copy disksort"
cp -av disksort $dest

echo "copy yazerc-disks.txt to $dest/.yazerc"
cp yazerc-disks.txt $dest/.yazerc

echo "End copy disks"


# echo -e "\nBegin copy documentation"
# mkdir $dest/doc
# for dfile in `cat docfiles.txt` ; do
#    cp -v $dfile $dest/doc
# done
# echo "End copy documentation"

echo -e "\nBegin copy HTML documentation"
mkdir $dest/doc_html
for dfile in `cat docfiles_html.txt` ; do
   cp -v $dfile $dest/doc_html
done

echo -e "\nBegin copy HTML version of HELP.HLP"
mkdir $dest/doc_html/cpmhelp
for dfile in `cat doc_cpmhelp_html.txt` ; do
   cp -v $dfile $dest/doc_html/cpmhelp
done
echo "End copy HTML documentation"

echo -e "\nCopy .minttyrc to $dest"
cp -v $HOME/.minttyrc $dest

echo -e "\nCopy the windows directory to $dest"
cp -v windows/* $dest

echo -e "\ngenerate md5 checksumms"
cd $dest
find . -type f -exec md5sum -b {} >>../yaze-ag.md5 \;
cd ..
mv yaze-ag.md5 $dest
